#you can add the trigger to execute this pipelines
trigger:
- master

variables:
  job-build: true

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: PrepareToExecuteJob
  jobs:
  - job: ExecuteLint
    steps:
    - script: |
        sudo npm install jsonlint -g
    - task: Bash@3
      inputs:
        filePath: './pipelines/pipelines-example01/scripts/hello_world.sh'
      displayName: 'HelloWorld'
    - script: tar -cvzf hello-world.tar.gz log.txt
      displayName: 'Create zip to upload'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: $(Build.SourcesDirectory)/hello-world.tar.gz
        artifactName: HelloFile
- stage: BuildApp
  jobs:
  - job: dockerBuild
    steps:
    - script: echo 'docker build'
    condition: eq(variables.job-build)
