#you can add the trigger to execute this pipelines
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: PrepareToExecuteJob
  jobs:
  - job: ExecuteLint
    steps:
    - script: |
        sudo npm install jsonlint -g
    - task: Bash@3
      inputs:
        filePath: '.azure-pipelines/hello_world.sh'
      displayName: 'HelloWorld'
    - script: tar -cvzf hello-world.tar.gz json/
      displayName: 'Create file to upload'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: $(Build.SourcesDirectory)/hello-world.tar.gz
        artifactName: HelloFile
- stages: BuildApp
  jobs:
  - job: dockerBuild
    steps:
    - script: echo 'docker build'
